### ISSUE TITLE
[WOW classic] Do not know how to use it ...

### ISSUE THREAD

**Issue by ekimmerst** [doadin/PlexusStatusAltRole#1]
Hi There.

I was searching for a Plexus addon to display the roles and found this addon. However, I do not know how to use it. In the Plexus options, I see the settings for this addon and I can assign the status to e.g. the top indicator or any other one. But I just do not see anything happen.

How do I use this plugin corecctly?

Thanks a lot.

**Comment by doadin** [comment]
Sorry, releasing for classic was a error. This plugin does NOT support classic. Support is unlikely to happen as it uses libGroupInSpecT to get info about player and they do not support classic. Sorry for any inconvenience.

**Comment by ekimmerst** [comment]
Oh, I see, no problem :)
